In [6]:
import pandas as pd
df = pd.read_csv("data/Anonymized_Free-form_PII_Dataset.csv")
df[:5].to_csv("./data/5rows.csv")

In [ ]:
from pprint import pprint
from comprehend_detect import ComprehendDetect
import pandas as pd
import boto3
from botocore.exceptions import ClientError

df = pd.read_csv("data/pii_test_faker.csv", nrows=50)
comp_detect = ComprehendDetect(boto3.client("comprehend","us-east-1"))

def detect_names(df, rows=5):
    df_names = pd.DataFrame()
    for i in range(rows):
        for col in df.columns:
            name_list = comp_detect.detect_entities(str(df[col][i]), 'en')
            for name in name_list:
                if name['Type'] == "PERSON":
                    name['field'] = col
                    name['row'] = i+1
                    print(name)
                    df_names = pd.concat([df_names,pd.DataFrame([name])])
    pprint(df_names.head())

    return df_names
detect_names(df,50)

{'Score': 0.9998224377632141, 'Type': 'PERSON', 'Text': 'Jeffrey Chavez', 'BeginOffset': 15, 'EndOffset': 29, 'field': 'sentence', 'row': 8}
{'Score': 0.9991254210472107, 'Type': 'PERSON', 'Text': 'Sherry Decker', 'BeginOffset': 0, 'EndOffset': 13, 'field': 'info3', 'row': 8}
{'Score': 0.9996781349182129, 'Type': 'PERSON', 'Text': 'David Bradley', 'BeginOffset': 17, 'EndOffset': 30, 'field': 'sentence', 'row': 9}
{'Score': 0.9994838237762451, 'Type': 'PERSON', 'Text': 'Matthew Arroyo', 'BeginOffset': 0, 'EndOffset': 14, 'field': 'info4', 'row': 9}
{'Score': 0.994425892829895, 'Type': 'PERSON', 'Text': 'Crystal Robinson', 'BeginOffset': 0, 'EndOffset': 16, 'field': 'info1', 'row': 12}
{'Score': 0.999467670917511, 'Type': 'PERSON', 'Text': 'Mark Perez', 'BeginOffset': 0, 'EndOffset': 10, 'field': 'info2', 'row': 12}
{'Score': 0.9994277358055115, 'Type': 'PERSON', 'Text': 'Danielle Lee', 'BeginOffset': 0, 'EndOffset': 12, 'field': 'info4', 'row': 15}
{'Score': 0.9988482594490051, 'Type': 'PERSON', 'Text': 'Javier Ramirez', 'BeginOffset': 11, 'EndOffset': 25, 'field': 'sentence', 'row': 16}
{'Score': 0.692751944065094, 'Type': 'PERSON', 'Text': 'Terrace', 'BeginOffset': 51, 'EndOffset': 58, 'field': 'sentence', 'row': 16}
{'Score': 0.6302009224891663, 'Type': 'PERSON', 'Text': 'director', 'BeginOffset': 0, 'EndOffset': 8, 'field': 'info1', 'row': 17}
{'Score': 0.999721348285675, 'Type': 'PERSON', 'Text': 'Melissa Hernandez', 'BeginOffset': 39, 'EndOffset': 56, 'field': 'sentence', 'row': 21}
{'Score': 0.9991575479507446, 'Type': 'PERSON', 'Text': 'Vanessa Cochran', 'BeginOffset': 11, 'EndOffset': 26, 'field': 'sentence', 'row': 24}
{'Score': 0.9937154054641724, 'Type': 'PERSON', 'Text': 'Tammy Harbors', 'BeginOffset': 6, 'EndOffset': 19, 'field': 'info2', 'row': 24}
{'Score': 0.9985345005989075, 'Type': 'PERSON', 'Text': 'Candace Key', 'BeginOffset': 6, 'EndOffset': 17, 'field': 'info3', 'row': 24}
{'Score': 0.9996336102485657, 'Type': 'PERSON', 'Text': 'Tammie Hanson', 'BeginOffset': 0, 'EndOffset': 13, 'field': 'info3', 'row': 25}
{'Score': 0.9997067451477051, 'Type': 'PERSON', 'Text': 'Erika Terry', 'BeginOffset': 39, 'EndOffset': 50, 'field': 'sentence', 'row': 26}
{'Score': 0.9996679425239563, 'Type': 'PERSON', 'Text': 'Lisa Morris', 'BeginOffset': 0, 'EndOffset': 11, 'field': 'info4', 'row': 26}
{'Score': 0.9997771978378296, 'Type': 'PERSON', 'Text': 'Paul Williams', 'BeginOffset': 15, 'EndOffset': 28, 'field': 'sentence', 'row': 34}
{'Score': 0.9997804164886475, 'Type': 'PERSON', 'Text': 'Kevin Rivas', 'BeginOffset': 15, 'EndOffset': 26, 'field': 'sentence', 'row': 36}
{'Score': 0.9997760653495789, 'Type': 'PERSON', 'Text': 'Mary Rogers', 'BeginOffset': 0, 'EndOffset': 11, 'field': 'sentence', 'row': 37}
{'Score': 0.9995344877243042, 'Type': 'PERSON', 'Text': 'David Ramirez', 'BeginOffset': 19, 'EndOffset': 32, 'field': 'sentence', 'row': 38}
{'Score': 0.9997284412384033, 'Type': 'PERSON', 'Text': 'Jeremy Dalton', 'BeginOffset': 0, 'EndOffset': 13, 'field': 'info3', 'row': 45}
{'Score': 0.9986720681190491, 'Type': 'PERSON', 'Text': 'Phillip Garrett', 'BeginOffset': 0, 'EndOffset': 15, 'field': 'info3', 'row': 46}
      Score    Type              Text  BeginOffset  EndOffset     field  row
0  0.999822  PERSON    Jeffrey Chavez           15         29  sentence    8
0  0.999125  PERSON     Sherry Decker            0         13     info3    8
0  0.999678  PERSON     David Bradley           17         30  sentence    9
0  0.999484  PERSON    Matthew Arroyo            0         14     info4    9
0  0.994426  PERSON  Crystal Robinson            0         16     info1   12

      Score    Type               Text  BeginOffset  EndOffset     field  row
0  0.999822  PERSON     Jeffrey Chavez           15         29  sentence    8
0  0.999125  PERSON      Sherry Decker            0         13     info3    8
0  0.999678  PERSON      David Bradley           17         30  sentence    9
0  0.999484  PERSON     Matthew Arroyo            0         14     info4    9
0  0.994426  PERSON   Crystal Robinson            0         16     info1   12
0  0.999468  PERSON         Mark Perez            0         10     info2   12
0  0.999428  PERSON       Danielle Lee            0         12     info4   15
0  0.998848  PERSON     Javier Ramirez           11         25  sentence   16
0  0.692752  PERSON            Terrace           51         58  sentence   16
0  0.630201  PERSON           director            0          8     info1   17
0  0.999721  PERSON  Melissa Hernandez           39         56  sentence   21
0  0.999158  PERSON    Vanessa Cochran           11         26  sentence   24
0  0.993715  PERSON      Tammy Harbors            6         19     info2   24
0  0.998535  PERSON        Candace Key            6         17     info3   24
0  0.999634  PERSON      Tammie Hanson            0         13     info3   25
0  0.999707  PERSON        Erika Terry           39         50  sentence   26
0  0.999668  PERSON        Lisa Morris            0         11     info4   26
0  0.999777  PERSON      Paul Williams           15         28  sentence   34
0  0.999780  PERSON        Kevin Rivas           15         26  sentence   36
0  0.999776  PERSON        Mary Rogers            0         11  sentence   37
0  0.999534  PERSON      David Ramirez           19         32  sentence   38
0  0.999728  PERSON      Jeremy Dalton            0         13     info3   45
0  0.998672  PERSON    Phillip Garrett            0         15     info3   46